# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Setup C/C++ make env
      - name: setup build env
        run: |
          sudo apt-get update
          sudo apt-get install clang make cmake gcc
          
      # Runs a set of commands using the runners shell
      - name: download coreutils & prepare
        run: |
          wget http://ftp.gnu.org/gnu/coreutils/coreutils-8.32.tar.xz
          tar xvJf coreutils-8.32.tar.xz
          cd coreutils-8.32/
          wget https://raw.githubusercontent.com/jarun/advcpmv/master/advcpmv-0.8-8.32.patch

      # Build
      - name: configure and build
        run: |
          cd coreutils-8.32/
          patch -p1 -i advcpmv-0.8-8.32.patch
          ./configure
          make
          mkdir target
          cp src/cp target/cpg
          cp src/mv target/mvg
          
      # Upload
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: 'coreutils-8.32/target/'
